### ISSUE TITLE
Hacer cartel para la defensa

### ISSUE THREAD

**Issue by daniarnaizg** [daniarnaizg/TFG-Amazon-Scraper#43]

**Comment by daniarnaizg** [comment]
![boceto_cartel_1](https://user-images.githubusercontent.com/23025125/60773531-26d75500-a107-11e9-9e1e-da76b4023e2c.jpg)

Boceto para el cartel

**Comment by daniarnaizg** [comment]
Primera versión:

![CARTEL-A0-peq](https://user-images.githubusercontent.com/23025125/60796078-178af280-a16d-11e9-96a5-7e10c0890f84.jpg)

**Comment by daniarnaizg** [comment]
Cartel final con algunos cambios:
![CARTEL-A0-peq](https://user-images.githubusercontent.com/23025125/60890861-724f4780-a25c-11e9-8b8c-1c29c0d5745f.jpg)

**Comment by mpl0045** [comment]
Muy bien

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________
